# Site settings
title: IB-BAUWESEN
description: "Wir als Ingenieurbüro für Bauwesen sind Dienstleister für private und öffentliche Auftraggeber im Dreiländereck Brandenburg, Sachsen und Sachsen-Anhalt."

baseurl: "" # the subpath of your site, e.g. /blog
url: "ib-bauwesen.julimage.de" # the base hostname & protocol for your site

collections:
- kernleistungen
- leistungen
